manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: touchpanel
      url-base: https://github.com/FrostKiwi
  projects:
    - name: zmk
      remote: touchpanel
      revision: mouse-3.2
      import: app/west.yml
  self:
    path: config
